name: Deploy

on:
  push:
    branches: [ feature/fix-ci ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/${{ secrets.USERNAME }}/Web/
            git pull origin develop
            docker compose -f ./docker/compose.prod.yml up -d --build
            echo "Deployed successfully !"