name: Deploy

on:
  push:
    branches: [ feature/ci-cd ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:       
    - name: Deploy using ssh
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd /home/contabo_user/Voisin-comme-cochon/Web
          git pull origin develop
          npm install
          docker-compose -f compose.prod.yml up -d