name: Deploy

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/contabo_user/Voisin-comme-cochon/Web/
            git pull origin develop
            npm install
            cd /home/contabo_user/Voisin-comme-cochon/Web/packages/frontend
            npm run build
            cd /home/contabo_user/Voisin-comme-cochon/Web/packages/backend
            npm run build
            cd /home/contabo_user/Voisin-comme-cochon/Web/packages/docker
            docker-compose -f compose.prod.yml up -d
            echo "Deployed successfully !"